language: node_js
node_js:
   - "6.*"

branches:
  only:
    - master

before_install:
  - npm i rollup eslint @gianlucaguarini/eslint-config -g
  - npm run build

notifications:
    email: false

sudo: false
